"""
@file exit_program.py

@brief Cleanup temporary files and exit gracefully.

Copyright (C) 2023-2025 The Board of Trustees of the University of Illinois.
All rights reserved.

This file is part of PlasFlowSolver: a data reduction model for ICP wind tunnels.

PlasFlowSolver is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

PlasFlowSolver is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with PlasFlowSolver.  If not, see 
<http://www.gnu.org/licenses/>.
"""

#.................................................
#   EXIT_PROGRAM.PY, v2.0.0, December 2024, Domenico Lanza.
#.................................................
#   This module is needed to clean the temporary
#   files generated by the program.
#.................................................
import os
from utils.mpp_memory_fixer import delete_mixture_file  # Function to delete the mixture file
from utils.classes import ProgramConstants

def clean_files():
    """This function is used to clean the temporary files.
    """
    # Constants
    program_constants = ProgramConstants()
    MIXTURE_NAME = program_constants.TemporaryFiles.TEMP_MIXTURE_NAME
    USE_PREV_ITE_FILENAME = program_constants.TemporaryFiles.USE_PREV_ITE_FILENAME
    X_VAR_FILENAME = program_constants.TemporaryFiles.X_VAR_FILENAME
    Y_VAR_FILENAME = program_constants.TemporaryFiles.Y_VAR_FILENAME
    Z_VAR_FILENAME = program_constants.TemporaryFiles.Z_VAR_FILENAME
    try:
        os.remove(USE_PREV_ITE_FILENAME) 
    except:
        pass
    try: 
        os.remove(X_VAR_FILENAME) 
        os.remove(Y_VAR_FILENAME) 
        os.remove(Z_VAR_FILENAME) 
    except:
        pass
    delete_mixture_file(MIXTURE_NAME)
    return

def exit_program():
    """This function is used to kill the program.
    """
    clean_files()
    print("The program has been killed. Please see the previous errors for more information.")
    exit()

#.................................................
#   Possible improvements:
#   -None
#.................................................
#   KNOW PROBLEMS:
#   None
#.................................................